source .env

DJANGO_SUPERUSER_EMAIL=$DJANGO_SUPERUSER_EMAIL \
DJANGO_SUPERUSER_PASSWORD=$DJANGO_SUPERUSER_PASSWORD \
DJANGO_SUPERUSER_FIRST_NAME=$DJANGO_SUPERUSER_FIRST_NAME \
DJANGO_SUPERUSER_LAST_NAME=$DJANGO_SUPERUSER_LAST_NAME \
python manage.py createsuperuser --no-input
