# Generated by Django 3.1 on 2020-09-03 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('number_of_rounds', models.IntegerField(default=0)),
                ('number_of_players', models.IntegerField()),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('inProgress', 'In progress'), ('completed', 'Completed')], default='setup', max_length=16)),
                ('game_type', models.CharField(choices=[('hannibal', 'Hannibal'), ('uno', 'Uno')], max_length=32)),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_first_dealer', models.BooleanField()),
                ('position', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
            ],
            options={
                'db_table': 'players',
            },
        ),
    ]
