# Generated by Django 3.1 on 2020-09-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_rounds', models.IntegerField(default=0)),
                ('number_of_players', models.IntegerField(default=0)),
                ('status', models.CharField(default='setup', max_length=16)),
                ('game_type', models.CharField(max_length=32)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'games',
            },
        ),
    ]
