# Generated by Django 3.1 on 2020-09-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200907_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='number_of_cards',
            field=models.IntegerField(default=0),
        ),
    ]
